site_name: Samir Romdhani - Full Stack Developer | Open Source Enthusiast
site_author: Samir Romdhani
site_url: "https://romdhanisam.github.io/portfolio/"
#repo_url: "https://github.com/romdhanisam/portfolio/"
#repo_name: "romdhanisam/portfolio"
docs_dir: docs
site_dir: public

nav:
  - Home: index.md
  - Work experience: projects.md
  - Contributions: contributions.md
  - Certifications: certifications.md
  - Articles: articles.md

theme:
  name: material
  favicon: https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/materialformkdocs.svg
  custom_dir: docs/overrides
  features:
    - toc.integrate
    - navigation.tabs
    - navigation.footer
markdown_extensions:
  - admonition
  - def_list
  - attr_list
  - footnotes
  - neoteroi.timeline
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      linenums_style: pymdownx.inline
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - md_in_html
extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/neoteroi-mkdocs.css

extra_javascript:
  - 'assets/javascripts/extra.js'

#extra:
#  social:
#    - icon: material/linkedin
#      link: https://www.linkedin.com/in/chikeegonu/
#      name: My LinkedIn Profile
#    - icon: octicons/person-fill-24
#      link: https://mrchike.github.io/chikeegonu/
#      name: My Projects Portfolio️
#    - icon: fontawesome/brands/github
#      link: https://github.com/MrChike
#      name: My Github Profile
