site_name: Samir Romdhani - Full Stack Developer | Open Source Enthusiast
site_author: Samir Romdhani
site_url: "https://romdhanisam.github.io/portfolio/"
#repo_url: "https://github.com/romdhanisam/portfolio/"
#repo_name: "romdhanisam/portfolio"
docs_dir: docs
site_dir: public
nav:
  - Accueil: 'index.md'
  - Membres:
      - 'Enseignant.e.s du secondaire' : membres/membres-sec.md
      - 'Enseignant.e.s du supérieur' : membres/membres-sup.md
      - 'Soutiens' : membres/soutiens.md
  - Journées :
      - 'Journée NSI 2025' : journees/2025.md
      - 'Journée NSI 2024' : journees/2024.md
#      - 'Journée NSI 2023' : journees/2023.md
#      - 'Journée NSI 2022' : journees/2022.md
#      - 'Journée NSI 2020' : journees/2020.md
#      - 'Journée ISN 2019' : journees/2019.md
#      - 'Journée ISN 2018' : journees/2018.md
#      - 'Journée ISN 2017' : journees/2017.md
#      - 'Journée ISN 2016' : journees/2016.md
#      - 'Journée ISN 2015' : journees/2015.md
#      - 'Journée ISN 2014' : journees/2014.md
#      - 'Journée ISN 2013' : journees/2013.md
#      - 'Journées SIF et ISN 2013' : journees/sif2013.md
  - Ressources :
#      - 'Didapro 7 - Didastic' : "http://didapro.org/7/"
#      - 'Didapro 8 - Didastic' : "https://www.didapro.org/8/"
#      - 'Didapro 9 - Didastic' : "https://www.didapro.org/9/"
#      - 'Didapro 10 - Didastic' : "https://www.didapro.org/10/"
      - 'Scratch' : scratch.md
theme:
  name: material
  custom_dir: custom_theme
plugins:
  - search:
      lang: fr
extra_css:
  - css/extra.css
  - css/neoteroi-mkdocs.css
markdown_extensions:
  - admonition
  - neoteroi.cards
  - neoteroi.timeline
  - neoteroi.spantable

